---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nominatim-app
  labels:
    app: nominatim-app
spec:
  replicas: 1
  serviceName: nominatim-app-svc
  selector:
    matchLabels:
      app: nominatim-app
  template:
    metadata:
      labels:
        app: nominatim-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/arch"
                operator: In
                values: ["amd64"]
      containers:
      - name: nominatim-app
        image: ghcr.io/bikehopper/nominatim-docker@sha256:46ff49c68423989806b42b862cdcf47495451502a13a524d017fa892430dadb2
        volumeMounts:
        - mountPath: /var/lib/postgresql/12
          name: nominatim-hostpath-pvc
        ports:
          - containerPort: 8080
          - containerPort: 5432
        resources:
          requests:
            memory: "2Gi"
            cpu: "1500m"
        env:
        - name: PBF_URL
          value: http://proxy-cache-svc.staging/geofabrik/north-america/us/california/norcal-latest.osm.pbf
        - name: REPLICATION_URL
          value: http://proxy-cache-svc.staging/geofabrik/north-america/us/california-updates
        - name: IMPORT_WIKIPEDIA
          value: 'true'
        - name: PROXY_SERVICE_NAME
          value: proxy-cache-svc
        - name: IMPORT_US_POSTCODES
          value: 'true'
        - name: IMPORT_TIGER_ADDRESSES
          value: 'true'
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NOMINATIM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nominatim-db
              key: password
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 10
      imagePullSecrets:
      - name: dockerconfigjson-github-com
  volumeClaimTemplates:
  - metadata:
      name: nominatim-hostpath-pvc
    spec:
      storageClassName: openebs-hostpath
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nominatim-app-svc
  labels:
    run: nominatim-app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: portgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: nominatim-app
